---
- hosts: all
  become: yes
  vars_files:
    - vars.yml
    - group_vars/all.yml
    - group_vars/vault.yml


  pre_tasks:
    - name: Debug vars
      debug:
        var: postgresql_log_dir
        
        
  roles:
    - geerlingguy.postgresql

  tasks:
    - name: Create table for dummy data
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: >
          CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100),
            email VARCHAR(100)
          );
      become: yes
      become_user: postgres

    - name: Insert dummy data
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: "{{ dummy_data_query }}"
      become: yes
      become_user: postgres