---
- hosts: solr
  become: true

  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        
  handlers:
    - name: Restart solr
      ansible.builtin.service:
        name: solr
        state: restarted
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - default-jdk
    - name: Download solr package
      ansible.builtin.command:
        cmd: wget https://archive.apache.org/dist/lucene/solr/8.9.0/solr-8.9.0.tgz
    - name: Unarchive solr 
      ansible.builtin.command:
        cmd: sudo tar xzf solr-8.9.0.tgz
    - name: Install Apache solr
      ansible.builtin.command:
        cmd: sudo bash solr-8.9.0/bin/install_solr_service.sh solr-8.9.0.tgz
    - name: Enable Solr service
      ansible.builtin.systemd:
        name: solr
        enabled: yes
        daemon_reload: yes
        