---
- hosts: all
  become: true

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      changed_when: false

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Remove the custom nginx index file
      ansible.builtin.file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    - name: Copy HTML file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0664'
        
    - name:  Create config file 
      ansible.builtin.copy:
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  root /var/www/html;
                  index index.html index.htm;
              }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0664'
      notify: Restart Nginx

