---
- name: Retrieve secret using aws_secret lookup
  ansible.builtin.set_fact:
    my_secret: "{{ lookup('amazon.aws.aws_secret', data) }}"

- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    # key_name: "prod-ssh-key"
    # vpc_subnet_id: subnet-013744e41e8088axx
    instance_type: "{{ instance_type }}"
    security_group: default
    region: "{{region}}"
    aws_access_key: "{{my_secret.aws_access_key}}"
    aws_secret_key: "{{my_secret.aws_secret_key}}"
    network:
      assign_public_ip: true
    image_id: "{{image_id}}"
    tags:
      Environment: Testing
